// js/projects.js — single source of truth for all project data
const PROJECTS = [
  {
    id:          'finance-tracker',
    week:        1,
    title:       'Finance Tracker',
    category:    'Finance · AI',
    description: 'Upload your bank statement and AI automatically recategorises your spending into a clean visual breakdown.',
    icon:        '💰',
    tags:        ['Python', 'Claude AI', 'Data Viz'],
    status:      'Live',
    buildCost:   '~$20',
    monthlyCost: '$0',
    page:        'finance-tracker.html',
    skills: {
      confident: ['Data Processing', 'Claude AI Integration', 'Python Scripting'],
      learning:  ['Data Visualisation'],
    },
    complexity: { backend: 70, frontend: 20, ai: 80 },
  },
  {
    id:          'color-fit',
    week:        2,
    title:       'Color-Fit',
    category:    'Web App · Design',
    description: 'TBD — fill in before launch.',
    icon:        '🎨',
    tags:        ['TBD'],
    status:      'Live',
    buildCost:   '~$20',
    monthlyCost: '$0',
    page:        'color-fit.html',
    skills: {
      confident: [],
      learning:  [],
    },
    complexity: { backend: 0, frontend: 0, ai: 0 },
  },
  {
    id:          'dream-future-quiz',
    week:        3,
    title:       'Dream Future Quiz',
    category:    'Web App · Quiz',
    description: 'A personality quiz that maps your dreams and ambitions to a future career path.',
    icon:        '🔮',
    tags:        ['Next.js', 'Vercel', 'JavaScript'],
    status:      'Live',
    buildCost:   '~$20',
    monthlyCost: '$0',
    page:        'dream-future-quiz.html',
    skills: {
      confident: ['Next.js', 'React', 'Vercel Deployment'],
      learning:  ['UX Flow Design'],
    },
    complexity: { backend: 10, frontend: 75, ai: 30 },
  },
  {
    id:          'watch-hunter',
    week:        4,
    title:       'Carousell Watch Hunter',
    category:    'Automation · Bot',
    description: 'Monitors Carousell SG every 15 minutes for undervalued Rolex, AP & RM watches. Sends a Telegram alert with one-tap auto-message to the seller.',
    icon:        '⌚',
    tags:        ['Python', 'Playwright', 'Telegram API', 'SQLite'],
    status:      'Live',
    buildCost:   '~$20',
    monthlyCost: '~$5',
    page:        'watch-hunter.html',
    skills: {
      confident: ['Web Scraping', 'Async Python', 'Bot Architecture', 'API Integration'],
      learning:  ['VPS Deployment', 'Rate Limiting'],
    },
    complexity: { backend: 85, frontend: 0, ai: 55 },
  },
  {
    id:          'jobber',
    week:        5,
    title:       'Jobber',
    category:    'iOS App · AI',
    description: 'Tinder-style job search for iOS. Swipe right to apply, left to skip. AI auto-tailors your resume per role and tracks every application.',
    icon:        '💼',
    tags:        ['React Native', 'Expo', 'Supabase', 'GPT-4'],
    status:      'In Progress',
    buildCost:   '~$20',
    monthlyCost: '$0',
    page:        'jobber.html',
    skills: {
      confident: ['React Native', 'Supabase', 'Mobile UI'],
      learning:  ['iOS Deployment', 'AI Resume Parsing'],
    },
    complexity: { backend: 65, frontend: 80, ai: 70 },
  },
  {
    id:          'stocks-manager',
    week:        6,
    title:       'Stocks Manager',
    category:    'Trading · Dashboard',
    description: 'A real-time trading dashboard with live market data, portfolio tracking, AI-powered alerts, and a full component system.',
    icon:        '📈',
    tags:        ['Python', 'Claude AI', 'React'],
    status:      'Live',
    buildCost:   '~$20',
    monthlyCost: '$0',
    page:        'stocks-manager.html',
    skills: {
      confident: ['React', 'Python Backend', 'Real-Time Data', 'Claude AI'],
      learning:  ['WebSocket Streams', 'Financial APIs'],
    },
    complexity: { backend: 80, frontend: 85, ai: 75 },
  },
];
